name: electron Builder
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions: write-all

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest]
        include:
          - os: macos-latest
            rust_target: x86_64-apple-darwin
          - os: macos-latest
            rust_target: aarch64-apple-darwin
          - os: windows-latest
            rust_target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      # for projects that use labels and PRs,
      # try https://github.com/mikepenz/release-changelog-builder-action instead
      # TODO: use API to collect commit messages
      - name: Build Changelog
        id: build_changelog
        run: echo "changelog=- ADD CHANGELOG" >> $GITHUB_OUTPUT

      - name: Node.js setup
        uses: actions/setup-node@v4
        # NOTE: enterprise developers may hard code a version
        with:
          node-version: 20
          # node-version-file: '.nvmrc'

      - name: Install app dependencies from lockfile and build web
        # NOTE: comment out && yarn build if frontend does not have build script
        run: npm install

      - name: Build the app
        run: npm run publish

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
